# Generated by Django 4.1.5 on 2023-02-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='action',
            name='actions_act_target__2d4e22_idx',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='target_cd',
            new_name='target_ct',
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['target_ct', 'target_id'], name='actions_act_target__f20513_idx'),
        ),
    ]
